image: arwineap/docker-debian-python3.6


pages:
  script:
  - apt-get update -qq
  - apt-get install -y -qq python3-pip libgl1-mesa-dev
  - pip3 install -r requirements.txt
  - pip3 install -r docs/requirements.txt
  - mkdir public
  - sphinx-build -n -v -a -b html ./docs ./public/
  artifacts:
    paths:
    - public
  only:
  - help_docs
